name: hangoverperth
favicon: null
layout_spectrum: 0.1316416955087334
typography_spectrum: 0.4324591963086277
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.18350270483642817
  lightness: 0.25622721994295716
  saturation: 0.06130810268223286
  rhythmicContrast: 0.10686922026798129
purpose: []
