name: hangoverperth
favicon: null
layout_spectrum: 0.25146
typography_spectrum: 1
title: Hangover treatment in Perth
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-2837827-4
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f2f2f0'
    - '#61706b'
    - '#aaa994'
    - '#463626'
    - '#13100b'
  brandStrength: 0.18350270483642817
  lightness: 0.25622721994295716
  saturation: 0.06130810268223286
  rhythmicContrast: 0.10686922026798129
purpose: []
